[vlc]
; VLCの 設定 > すべて表示 > インターフェース > メインインターフェース > Lua
; で設定したパスワードを入力してください
password = your_password_here

; 通常は変更不要
host = 127.0.0.1
port = 8080

; 削除実行のホットキー (keyboardライブラリの記法に従う)
hotkey = ctrl+alt+d
